@startuml context
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Пользователь", "Любой человек, пользующийся системой")
Person(mod, "Модератор", "Пользователь, наделенный правами на модерацию контента")
Person(admin, "Администратор", "Внутренний пользователь с правами на администрирование системы")
System_Ext(externalSystems, "Внешние системы", "Внешние системы, которые получают доступ к результатам опросов через API")
System(system, "Система", "Интернет площадка для проведения опросов и визуализации результатов")

Rel(user, system, "Создание, прохождение опросов. Просмотр и выгрузка результатов. Оценка и комментирование публикаций")
Rel(mod, system, "Просмотр жалоб, удаление публикаций с неподобающим содержимым")
Rel_R(admin, system, "Администрирование системы. Назначение модераторов")
Rel_U(externalSystems, system, "Получение данных через API")
@enduml